# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0002_auto_20171115_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
