# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0003_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
