# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 13:15
from __future__ import unicode_literals

import Django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_agent',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, validators=[Django.models.min_length_3_validator], verbose_name='제목'),
        ),
    ]
