# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 03:49
from __future__ import unicode_literals

import Django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0005_auto_20171120_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[Django.models.min_length_3_validator]),
        ),
    ]
